version: 0.2

env:
  variables:
    RDS_DB_NAME: "blacklist_db"
    SECRET_KEY: "super-secret"
    JWT_SECRET_KEY: "super-secret"

phases:
  pre_build:
    commands:
      - pip install -r requirements.txt
  build:
    commands:
      - python3 -m pytest tests/test_unit.py

artifacts:
  files:
    - '**/*'
