version: 0.2

env:
  variables:
    RDS_DB_NAME: "blacklist_db"
    SECRET_KEY: "super-secret"
    JWT_SECRET_KEY: "super-secret"

phases:
  pre_build:
    commands:
      # - pip install awsebcli boto3
      - pip install -r requirements.txt
  build:
    commands:
      - gunicorn -b 0.0.0.0:8000 main:app

artifacts:
  files:
    - '**/*'
